[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.4"

[dev]
  framework = "#auto"

[functions]
  node_bundler = "esbuild"

[functions.environment]
  DATABASE_URL = "${env:DATABASE_URL}"
